apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-cs
spec:
  serviceName: "postgres-cs"
  replicas: 1
  selector:
    matchLabels:
      app: postgres-cs
  template:
    metadata:
      labels:
        app: postgres-cs
    spec:
      containers:
        - name: postgres-cs
          image: postgres
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-cs-secret
                  key: POSTGRES_PASSWORD
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: postgres-cs-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-cs-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: gp2
