apiVersion: v1
kind: Service
metadata:
  name: postgres-cs
  labels:
    app: postgres-cs
spec:
  type: ClusterIP
  selector:
    app: postgres-cs
  ports:
    - name: postgres-cs
      port: 5432
      targetPort: 5432
