apiVersion: apps/v1
kind: Deployment
metadata:
  name: collab-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collab-service
  template:
    metadata:
      labels:
        app: collab-service
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: collab-service
          image: peerprep4/peerprep4:collaboration_service
          imagePullPolicy: Always
          ports:
            - containerPort: 3009
          resources:
            requests:
              cpu: "200m"
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: cs-secret
                  key: DATABASE_URL
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: cs-secret
                  key: RABBITMQ_URL
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: cs-secret
                  key: REDIS_URL
            - name: PG_HOST
              valueFrom:
                secretKeyRef:
                  name: cs-secret
                  key: PG_HOST
            - name: PG_PORT
              valueFrom:
                secretKeyRef:
                  name: cs-secret
                  key: PG_PORT
            - name: PG_DATABASE
              valueFrom:
                secretKeyRef:
                  name: cs-secret
                  key: PG_DATABASE
            - name: PG_USER
              valueFrom:
                secretKeyRef:
                  name: cs-secret
                  key: PG_USER
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cs-secret
                  key: PG_PASSWORD
            - name: QUESTIONURL
              valueFrom:
                secretKeyRef:
                  name: cs-secret
                  key: QUESTIONURL

          readinessProbe:
            httpGet:
              path: /healthz
              port: 3009
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3009
