apiVersion: v1
kind: Secret
metadata:
  name: service-endpoints
type: Opaque
data:
  NEXT_PUBLIC_API_COLLAB_SERVICE: http://localhost:3009
  NEXT_PUBLIC_API_QUESTION_SERVICE: http://question-service:3008
  NEXT_PUBLIC_API_MATCHING_SERVICE: http://localhost:3007
  NEXT_PUBLIC_API_USER_SERVICE: http://localhost:3005
  NEXT_PUBLIC_API_CODE_EXE_SERVICE: http://localhost:3004
  NEXT_PUBLIC_API_COMMS_SERVICE: http://localhost:3003
