services:
  cs-postgres:
    image: postgres
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - '5439:5432'
    networks:
      - peerprep-network
    volumes:
      - collab_postgres_data:/collab_data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

    networks:
      - peerprep-network

  collaboration_service:
    build:
      context: ../../
      dockerfile: services/collaboration_service/Dockerfile

    restart: always
    depends_on:
      - cs-postgres
      # - redis
      # - rabbitmq
    ports:
      - '3012:3012'
    networks:
      - peerprep-network

    environment:
      - REDIS_URL=${REDIS_URL}
      - RABBITMQ_URL=${RABBITMQ_URL}
      - PG_HOST=${PG_HOST}
      - PG_PORT=${PG_PORT}
      - PG_DATABASE=${PG_DATABASE}
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}

      - DATABASE_URL=${DATABASE_URL}

volumes:
  collab_postgres_data:

networks:
  peerprep-network:
    external: true
