version: "3.9"
services:
  qs-postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports: ["5436:5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d qs"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - peerprep-network
    volumes:
      - user_postgres_data:/user_data

  question_service:
    build:
      context: .
      dockerfile: ./Dockerfile

    restart: always
    depends_on:
      - qs-postgres
    ports:
      - "3008:3008"
    networks:
      - peerprep-network

    environment:
      - DATABASE_URL=${DATABASE_URL_DOCKER}

      - JWT_ISSUER=${JWT_ISSUER}
      - JWKS_URL=${JWKS_URL}
      - JWT_AUDIENCE=${JWT_AUDIENCE}
      - ALLOW_ANONYMOUS_READS=${ALLOW_ANONYMOUS_READS}
      - SIGNED_URL_TTL_SECONDS=${SIGNED_URL_TTL_SECONDS}
      - S3_BUCKET=${S3_BUCKET}
      - ACCESS_KEY=${ACCESS_KEY}
      - SECRET_KEY=${SECRET_KEY}
      - AWS_REGION=${AWS_REGION}

volumes:
  user_postgres_data:

networks:
  peerprep-network:
    external: true
