version: "3.9"
services:
  qs-postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports: ["5436:5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d qs"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - peerprep-network
    volumes:
      - user_postgres_data:/user_data

volumes:
  user_postgres_data:

networks:
  peerprep-network:
    external: true
