version: "3.9"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: ylchin0715
      POSTGRES_USER: postgres
      POSTGRES_DB: qs
    ports: ["5435:5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d qs"]
      interval: 5s
      timeout: 3s
      retries: 10
