apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: question-service
  namespace: default
spec:
  parentRefs:
    - name: gateway
      sectionName: http
  # hostnames:
  # - "cafe.example.com"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /api/question-service
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /
      backendRefs:
        - name: question-service
          port: 3008
