apiVersion: v1
kind: Service
metadata:
  name: postgres-us
  labels:
    app: postgres-us
spec:
  type: ClusterIP
  selector:
    app: postgres-us
  ports:
    - name: postgres-us
      port: 5432
      targetPort: 5432
