apiVersion: apps/v1
kind: Deployment
metadata:
  name: comms-service
  labels:
    app: comms-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comms-service
  template:
    metadata:
      labels:
        app: comms-service
    spec:
      imagePullSecrets:
        - name: dockerhub-secret

      containers:
        - name: comms-service
          image: peerprep4/peerprep4:comms_service
          imagePullPolicy: Always
          ports:
            - containerPort: 3012
          env:
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: cms-secret
                  key: RABBITMQ_URL
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: cms-secret
                  key: REDIS_URL
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: cms-secret
                  key: PORT

          # readinessProbe:
          #   httpGet:
          #     path: /healthz
          #     port: 3012
          # livenessProbe:
          #   httpGet:
          #     path: /healthz
          #     port: 3012
