apiVersion: apps/v1
kind: Deployment
metadata:
  name: question-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: question-service
  template:
    metadata:
      labels:
        app: question-service
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: question-service
          image: peerprep4/peerprep4:question_service
          imagePullPolicy: Always
          ports:
            - containerPort: 3008
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: qs-secret
                  key: DATABASE_URL
            - name: ALLOW_ANONYMOUS_READS
              valueFrom:
                secretKeyRef:
                  name: qs-secret
                  key: ALLOW_ANONYMOUS_READS
            - name: SIGNED_URL_TTL_SECONDS
              valueFrom:
                secretKeyRef:
                  name: qs-secret
                  key: SIGNED_URL_TTL_SECONDS
            - name: S3_BUCKET
              valueFrom:
                secretKeyRef:
                  name: qs-secret
                  key: S3_BUCKET
            - name: ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: qs-secret
                  key: ACCESS_KEY
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: qs-secret
                  key: SECRET_KEY
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: qs-secret
                  key: AWS_REGION

          readinessProbe:
            httpGet:
              path: /healthz
              port: 3008
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3008
