apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-qs
spec:
  serviceName: "postgres-qs"
  replicas: 1
  selector:
    matchLabels:
      app: postgres-qs
  template:
    metadata:
      labels:
        app: postgres-qs
    spec:
      containers:
        - name: postgres-qs
          image: postgres:16
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-qs-secret
                  key: POSTGRES_PASSWORD
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata

          volumeMounts:
            - name: postgres-qs-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-qs-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: gp2
