name: Frontend
run-name: Frontend CI

on:
  workflow_call:

defaults:
  run:
    working-directory: frontend

jobs:
  lint-services:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Install lint
        run: pnpm i
      - name: lint frontend
        run: pnpm run lint -- src

  build-frontend:
    # needs: lint-services
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: build frontend
        run: pnpm i && pnpm run build

  build-and-push-docker-image:
    # needs: build-frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
       
      - name: Load env file
        run: |
          set -a
          source .env.public.prod 
          set +a
      
      - name: Verify env variables
        run: |
          export -p | grep NEXT_PUBLIC
        
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: peerprep4/peerprep4:frontend
          platforms: linux/arm64
